# Generated by Django 5.0.4 on 2024-09-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res_api', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=255, unique=True)),
                ('ProductPrice', models.CharField(max_length=255)),
                ('ProductLink', models.CharField(max_length=255)),
            ],
        ),
    ]
