# Generated by Django 5.0.4 on 2024-09-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res_api', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProductPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
