# Generated by Django 5.0.4 on 2024-09-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res_api', '0004_alter_product_productprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ProductCategory',
            field=models.CharField(default='General', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='ProductDescription',
            field=models.CharField(default='General', max_length=255),
            preserve_default=False,
        ),
    ]
